"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
#alkup
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# heroku BASE_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

#fb app id:1661776270702149
#fb secret:6d119506d8297bd9476db3a3886efcbc
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!$-^kgn&eu8l*hv6q89hf%s26-y%9_didhui=ikl%=)%)$p3s$'





DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites', # Required by 'allauth'
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'wmuser',
    'wmposts',
    'wmbitcoin',
    'wmcomment',
    'testing',
    # Social Authentication Packages
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    # Coinbase API, Bitcoin Integration
    'coinbase',
    # Twitter-Style Endless Pagination
    'endless_pagination',
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.core.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

WSGI_APPLICATION = 'app.wsgi.application'



# Database. Read https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'whizmilldb',                    
        'USER': 'test',
        'PASSWORD': 'tesla',
        'HOST': '',
        'PORT': '',
    }
}

#DATABASES = {
 #   'default': {
 #       'ENGINE': 'django.db.backends.sqlite3',
  #      'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),                   
#    },
    
#    'default': {
#        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'postgres',                      
#        'USER': 'postgres',
#        'PASSWORD': 'Teslavs.Ferrari69',
#        'HOST': '',
#        'PORT': '',
#    }
#}


# Internationalization. Read https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images). Read https://docs.djangoproject.com/en/1.8/howto/static-files/


STATIC_ROOT = 'staticfiles'
STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


#Media url
#pitaa jossain vaiheessa pistaa oikein.
#MEDIA_ROOT='../static'
#MEDIA_URL=''


# Allowed Image Formats

ALLOWED_UPLOAD_IMAGES = ('gif', 'jpeg', 'png', 'jpg')

# Password Hashing

PASSWORD_HASHERS = (
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.SHA1PasswordHasher',
    'django.contrib.auth.hashers.MD5PasswordHasher',
    'django.contrib.auth.hashers.CryptPasswordHasher',
)

# Registration stuff

# This is the number of days users will have to activate their accounts after registering. If a user does not activate within that period, the account will remain permanently inactive and may be deleted by maintenance scripts provided in django-registration-redux.
ACCOUNT_ACTIVATION_DAYS = 7;


#Optional. If this is True, your users will automatically log in when they  click on the activation link in their email. Defaults to False.
REGISTRATION_AUTO_LOGIN = True;

SITE_ID = 1

# SMTP and E-mail configuration settings
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'whizmilltesting2@gmail.com'
EMAIL_HOST_PASSWORD = 'ferraripojatlolxd'

# Endless Twitter-Style Pagination Settings
ENDLESS_PAGINATION_PER_PAGE=10

# Django AllAuth Settings
ACCOUNT_ADAPTER = 'wmuser.adapter.CustomAccountAdapter'

# Default User Model
AUTH_USER_MODEL = 'wmuser.BaseUser'


BTC_TO_UPVOTES = 0.00000395
BTC_TO_EUR = 253.16




#Heroku stuff
# Parse database configuration from $DATABASE_URL
import dj_database_url
DATABASES['default'] =  dj_database_url.config()

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = ['*']


